#!/bin/sh

# config
domain_name=local.dev.khaledez.net

# common functions
{
    log() {
        printf '\033[32m->\033[m %s\n' "$*"
    }

    die() {
        printf '\033[31m->\033[m %s\n' "$*" >&2
        exit 1
    }
}

# sub commands
{
    tf_website_dir="terraform/static-website"
    command_setup () {
        terraform init \
            -backend-config="key=local/local.dev.khaledez.net" \
            -get-plugins=true \
            -input=false \
            $tf_website_dir
        
        command_sync
    }

    command_sync () {
        zip $tf_website_dir/target/router.zip $tf_website_dir/router.js

        terraform apply \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=local" \
            $tf_website_dir
    }

    command_destroy () {
        terraform destroy \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=local" \
            $tf_website_dir
    }

    command_deploy () {
        aws s3 sync public/ s3://$domain_name
    }

    command_build () {
        yarn && yarn build
    }

    command_clean () {
        yarn clean
        rm -rf node_modules/
    }
}

[ "$1" ] || die "Usage: ./dev [setup|destroy|sync|deploy|build|clean]"
command_$1
