#!/bin/sh

# config
domain_name=local.dev.khaledez.net

# common functions
{
    pushd () {
        command pushd "$@" > /dev/null
    }

    popd () {
        command popd "$@" > /dev/null
    }

    log() {
        printf '\033[32m->\033[m %s\n' "$*"
    }

    die() {
        printf '\033[31m->\033[m %s\n' "$*" >&2
        exit 1
    }
}

# sub commands
{
    command_setup () {
        pushd "terraform/static-website"
        terraform init \
            -backend-config="key=local/local.dev.khaledez.net" \
            -get-plugins=true \
            -reconfigure \
            -input=false
        terraform apply -var "domain_name=$domain_name" -auto-approve
        popd
    }

    command_destroy () {
        pushd "terraform/static-website"
        terraform destroy
        popd
    }

    command_deploy () {
        aws s3 sync public/ s3://$domain_name
    }

    command_build () {
        yarn && yarn build
    }

    command_clean () {
        yarn clean
        rm -rf node_modules/
    }
}

[ "$1" ] || die "Usage: ./dev [setup|destroy|deploy|build|clean]"
command_$1
