#!/bin/sh

# config
domain_name=local.dev.khaledez.net

# common functions

log() {
    printf '\033[32m->\033[m %s\n' "$*"
}

die() {
    printf '\033[31m->\033[m %s\n' "$*" >&2
    exit 1
}

# sub commands
{
    tf_website_dir="terraform/static-website"
    command_init() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1
        terraform init \
            -backend-config="key=local/local.dev.khaledez.net" \
            -get-plugins=true \
            -input=false
        cd "$oldpath" || exit 1
    }

    command_sync() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1
        mkdir -p target
        zip -q target/router.zip router.js

        terraform apply \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=local"

        cd "$oldpath" || exit 1
    }

    command_destroy() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1
        rm -rf target/

        # manually untrack Lambda@Edge function, because it cannot be deleted !!!
        terraform state rm 'aws_lambda_function.router'

        terraform destroy \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=local"

        cd "$oldpath" || exit 1
    }

    command_deploy() {
        aws s3 sync public/ s3://$domain_name
    }

    command_build() {
        yarn && yarn build
    }

    command_clean() {
        yarn clean
        rm -rf node_modules/
    }
}

[ "$1" ] || die "Usage: ./dev [init|sync|destroy|deploy|build|clean]"
"command_$1"
