#!/bin/sh -e

# load config

## Default config
backend_s3=net.khaledez.terraform.backend
env_name=local
domain_name=local.dev.khaledez.net

# shellcheck source=/dev/null
. ./please.env
if [ -e .env ]; then
    # shellcheck source=/dev/null
    . .env
fi

# common functions

log() {
    printf '\033[32m->\033[m %s\n' "$*"
}

die() {
    printf '\033[31m->\033[m %s\n' "$*" >&2
    exit 1
}

# sub commands
{
    tf_website_dir="terraform/static-website"
    command_init() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1
        terraform init \
            -backend-config="key=$env_name/$domain_name" \
            -migrate-state
        cd "$oldpath" || exit 1
    }

    command_sync() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1

        terraform apply \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=$env_name" || exit 1

        cd "$oldpath" || exit 1
    }

    command_destroy() {
        oldpath=$(pwd)
        cd $tf_website_dir || exit 1

        terraform destroy \
            -auto-approve \
            -var "domain_name=$domain_name" \
            -var "environment=$env_name" || exit 1

        cd "$oldpath" || exit 1

        aws s3 rm "s3://$backend_s3/$env_name/$domain_name"
    }

    command_deploy() {
        aws s3 rm "s3://$domain_name" --recursive
        aws s3 sync dist/ "s3://$domain_name"
    }

    command_build() {
        exec npm run build
    }

    command_run() {
        exec npm run dev
    }

    command_clean() {
        rm -rf dist/
    }
}

[ "$1" ] || die "Usage: ./please [init|sync|destroy|deploy|build|run|clean]"
"command_$1"
