name: Delete PR website
on:
  pull_request:
    types: [closed]

jobs:
  delete:
    name: delete created website
    runs-on: ubuntu-20.04
    env:
      domain_name: ${{ format('pr-{0}.dev.khaledez.net', github.event.pull_request.number) }}
      cert_domain: "*.dev.khaledez.net"
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # London

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.x

      - name: Setup configuration
        run: |
          echo 'env_name=dev' > please.env
          echo 'domain_name=${{ env.domain_name }}' >> please.env
      
      - name: Terraform init
        run: sh ./please init
      
      - name: destroy resources
        run: |
          sh ./please destroy
        env:
          TF_VAR_cert_domain: ${{ env.cert_domain }}

