name: Delete PR website
on:
  pull_request:
    types: [closed]

jobs:
  delete:
    name: delete created website
    runs-on: ubuntu-18.04
    env:
      domain_name: ${{ format('pr-{0}.dev.khaledez.net', github.event.pull_request.number) }}
      cert_domain: "*.dev.khaledez.net"
      terraform_dir: "terraform/static-website"
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # London

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Terraform destroy resources
        run: |
          pushd ${{ env.terraform_dir }}
          terraform init -backend-config="key=pr/${{ env.domain_name }}"

          # manually untrack Lambda@Edge function, because it cannot be deleted !!!
          terraform state rm 'aws_lambda_function.router'
          terraform destroy -auto-approve 

          popd
        env:
          TF_VAR_domain_name: ${{ env.domain_name }}
          TF_VAR_cert_domain: ${{ env.cert_domain }}

      - name: Delete Terraform state
        run: |
          aws s3 rm s3://${{ env.terraform_backend_bucket }}/pr/${{ env.domain_name }}
