name: PR website
on:
  - pull_request

jobs:
  check-and-preview:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      domain_name: ${{ format('pr-{0}.preview.khaledez.net', github.event.pull_request.number) }}
      cert_domain: "*.preview.khaledez.net"
  