name: PR website
on:
  - pull_request

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-18.04
    env:
      domain_name: ${{ format('pr-{0}.dev.khaledez.net', github.event.pull_request.number) }}
      cert_domain: "*.dev.khaledez.net"
      terraform_dir: "terraform/static-website"
      terraform_version: 0.12.24
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform_version }}
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "${{ env.terraform_dir }}"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: yarn install, test
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build --if-present
        env:
          CI: true

      - name: create router lambda zipfile
        run: |
          pushd terraform/static-website
          zip target/router.zip router.js
          popd

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # London

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform_version }}
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "${{ env.terraform_dir }}"
          tf_actions_comment: true
          args: '-backend-config="key=pr/${{ env.domain_name }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform_version }}
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "${{ env.terraform_dir }}"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        id: "terraform_apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform_version }}
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "${{ env.terraform_dir }}"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_domain_name: ${{ env.domain_name }}
          TF_VAR_cert_domain: ${{ env.cert_domain }}

      - name: Copy files to S3 with AWS CLI
        run: |
          aws s3 sync public/ s3://${{ env.domain_name }}
