name: Create release package
on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Create a release package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: create ZIP
        env:
          GITHUB_TOKEN: {{ Secrets.GITHUB_TOKEN }}
          ASSET_NAME: khaledez.net.tar.gz
        run: |
          tar -zcvf $ASSET_NAME index.html
          echo $GITHUB_WORKPLACE

