name: Create release package
on:
  push:
    branches:
      - feature-automate-release

jobs:
  release:
    name: package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./

