name: release website
on:
  push:
    branches:
      - feature-automate-release

jobs:
  release:
    name: build and publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # London
      
      - name: Copy files to S3 with AWS CLI
        run: |
          aws s3 sync public/ s3://net.khaledez.www --acl public-read
          aws s3 website s3://net.khaledez.www --index-document index.html --error-document error.html