name: Create release package
on:
  push:
    branches:
      - feature-automate-release

jobs:
  release:
    name: package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
