name: release website
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
      domain_name: khaledez.net
      cert_domain: "khaledez.net"
      domain_aliases: '["www.khaledez.net"]'
      cache_ttl: 3600